In [ ]:
import numpy as np
import pandas as pd

In [ ]:
d = {
    'one' : ['I like cricket','cricket is good','I love cricket'],
    'two' : [1,0,1]
}

In [ ]:
df = pd.DataFrame(d)

In [ ]:
df.head()

               one  two
0   I like cricket    1
1  cricket is good    0
2   I love cricket    1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['one'])

In [ ]:
print(cv.vocabulary_)

{'like': 3, 'cricket': 0, 'is': 2, 'good': 1, 'love': 4}

In [ ]:
bow.toarray()

array([[1, 0, 0, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 1]])

In [ ]:
cv.transform(['cricket is my life']).toarray()

array([[1, 0, 1, 0, 0]])

In [ ]:
d2 = {
    'text' : ['I see a cat','The dog runs.','She is happy','The sun is hot','We like cake'],
    'output' : [0,0,1,1,1]
}

In [ ]:
df2 = pd.DataFrame(d2)

In [ ]:
df2.head()

             text  output
0     I see a cat       0
1   The dog runs.       0
2    She is happy       1
3  The sun is hot       1
4    We like cake       1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv2 = CountVectorizer(stop_words='english')
count_matrix = cv2.fit_transform(df2['text'])
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
count_matrix.toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0]])

In [ ]:
cv2.vocabulary_

{'cat': 1,
 'dog': 2,
 'runs': 6,
 'happy': 3,
 'sun': 7,
 'hot': 4,
 'like': 5,
 'cake': 0}

In [ ]:
cv3 = CountVectorizer(ngram_range=(2,2))
count_matrix3 = cv3.fit_transform(df2['text'])
cosine_sim3 = cosine_similarity(count_matrix3, count_matrix3)

In [ ]:
count_matrix.toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0]])

In [ ]:
cv3.vocabulary_

{'see cat': 4,
 'the dog': 7,
 'dog runs': 0,
 'she is': 5,
 'is happy': 1,
 'the sun': 8,
 'sun is': 6,
 'is hot': 2,
 'we like': 9,
 'like cake': 3}

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
tfidf.fit_transform(df2['text']).toarray()

array([[0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.61418897, 0.        , 0.        ,
        0.        , 0.        , 0.61418897, 0.        , 0.        ,
        0.        , 0.49552379, 0.        ],
       [0.        , 0.        , 0.        , 0.61418897, 0.        ,
        0.49552379, 0.        , 0.        , 0.        , 0.61418897,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.55032913,
        0.44400208, 0.        , 0.        , 0.        , 0.        ,
        0.55032913, 0.44400208, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027]])

In [ ]:
tfidf.get_feature_names_out()

array(['cake', 'cat', 'dog', 'happy', 'hot', 'is', 'like', 'runs', 'see',
       'she', 'sun', 'the', 'we'], dtype=object)

In [ ]:
tfidf.idf_

array([2.09861229, 2.09861229, 2.09861229, 2.09861229, 2.09861229,
       1.69314718, 2.09861229, 2.09861229, 2.09861229, 2.09861229,
       2.09861229, 1.69314718, 2.09861229])